### PR TITLE
add 'src' field to opts along with 'params' and 'splat'

### PR DESCRIPTION
**Pull request by Jonahss**
Hi, the original author seems unresponsive, but I noticed your PR which mentioned this fork.

Care to merge this small feature?

### CODE REVIEW

**Comment by bcomnes** [comment]
Hi @Jonahss I completely missed this. Let me take a look

**Comment by bcomnes** [comment]
Yeah this looks fine to me.  Let me get things in order on this repo.

**Comment by bcomnes** [comment]
Sorry, I think this fork is a dead end for now.  I recommend forking into your own repo and getting what you need there. Good luck!

**Comment by Jonahss** [comment]
okay

**Pull request closed without merging**
